version: '3.3'

services:
  zookeeper:
    image: zookeeper:latest
    hostname: zoo
    ports:
      - 2181:2181
    networks:
      - app
    
  kafka:
    image: dleo9307/kafka:2.13
    ports:
      - 9092:9092
    volumes:
      - ./config:/kafka/config
    command: kafka/bin/kafka-server-start.sh kafka/config/server.properties
    networks:
      - app

networks:
  app:
